// GT3 Corner Guide — Track Data
// Auto-generated by Edit Mode.

const tracks = [
  {
    "id": "brands_hatch",
    "name": "Brands Hatch",
    "country": "United Kingdom 🇬🇧",
    "corners": [
      {
        "id": "T1",
        "label": "Paddock Hill Bend",
        "gear": "3rd",
        "brakePoint": "",
        "speed": "",
        "notes": "",
        "imageFile": "t1.jpg",
        "x": 39.13,
        "y": 80.9
      }
    ]
  },
  {
    "id": "zolder",
    "name": "Zolder GP Circuit",
    "country": "Belgium 🇧🇪",
    "corners": [
      {
        "id": "T1",
        "label": "Mercedes Arena",
        "gear": "2nd",
        "brakePoint": "~100m",
        "speed": "~80 km/h",
        "notes": "Hard stop from high speed. Complex multi-apex section. Entry angle critical.",
        "imageFile": "t1.png",
        "x": 38,
        "y": 22
      },
      {
        "id": "T5",
        "label": "Ford Kurve",
        "gear": "3rd",
        "brakePoint": "~120m",
        "speed": "~105 km/h",
        "notes": "Medium-slow right-hander. Trail brake to apex. Exit feeds fast straight.",
        "imageFile": "t5.png",
        "x": 62,
        "y": 38
      },
      {
        "id": "T8",
        "label": "Schumacher S",
        "gear": "4th → 3rd",
        "brakePoint": "~90m",
        "speed": "~120 km/h",
        "notes": "Esses section. First apex leads second. Smooth inputs through here.",
        "imageFile": "t8.png",
        "x": 74,
        "y": 60
      },
      {
        "id": "T13",
        "label": "Hairpin",
        "gear": "2nd",
        "brakePoint": "~70m",
        "speed": "~65 km/h",
        "notes": "Slowest corner on circuit. Very late apex. Traction out is everything here.",
        "imageFile": "t13.png",
        "x": 46,
        "y": 75
      }
    ]
  }
];
